/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAnalytics {
  'popularEvents' : Array<RevenueByEvent>,
  'totalBookings' : bigint,
  'totalUsers' : bigint,
  'showtimeOccupancy' : Array<ShowtimeOccupancy>,
  'totalRevenueCents' : bigint,
}
export interface BookingFilter {
  'status' : [] | [BookingStatus],
  'showtimeId' : [] | [EntityId],
}
export interface BookingItem {
  'seatId' : EntityId,
  'seatLabel' : string,
  'category' : TicketCategory,
  'priceInCents' : bigint,
}
export interface BookingPublic {
  'id' : EntityId,
  'status' : BookingStatus,
  'refundStatus' : RefundStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'showtimeId' : EntityId,
  'cancelledAt' : [] | [Timestamp],
  'qrReference' : string,
  'totalAmountCents' : bigint,
  'items' : Array<BookingItem>,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export interface CreateBookingInput {
  'seatIds' : Array<EntityId>,
  'showtimeId' : EntityId,
}
export interface CreateEventInput {
  'title' : string,
  'imageUrls' : Array<string>,
  'description' : string,
  'genre' : string,
  'durationMinutes' : bigint,
  'eventType' : EventType,
}
export interface CreateShowtimeInput {
  'startTime' : Timestamp,
  'eventId' : EntityId,
  'venueId' : EntityId,
  'seatCategories' : Array<
    {
      'totalSeats' : bigint,
      'category' : TicketCategory,
      'priceInCents' : bigint,
    }
  >,
}
export interface CreateVenueInput {
  'name' : string,
  'totalSeats' : bigint,
  'address' : string,
  'layoutCols' : bigint,
  'layoutRows' : bigint,
}
export type EntityId = bigint;
export interface EventFilter {
  'title' : [] | [string],
  'dateTo' : [] | [Timestamp],
  'venueId' : [] | [EntityId],
  'maxPriceCents' : [] | [bigint],
  'dateFrom' : [] | [Timestamp],
  'minPriceCents' : [] | [bigint],
  'eventType' : [] | [EventType],
}
export interface EventPublic {
  'id' : EntityId,
  'title' : string,
  'imageUrls' : Array<string>,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'isActive' : boolean,
  'genre' : string,
  'durationMinutes' : bigint,
  'eventType' : EventType,
}
export type EventType = { 'movie' : null } |
  { 'concert' : null } |
  { 'workshop' : null } |
  { 'other' : null } |
  { 'sports' : null };
export type PaymentMode = { 'other' : null } |
  { 'card' : null };
export interface PaymentPublic {
  'id' : EntityId,
  'status' : PaymentStatus,
  'completedAt' : [] | [Timestamp],
  'bookingId' : EntityId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amountCents' : bigint,
  'paymentMode' : PaymentMode,
  'stripeSessionId' : [] | [string],
  'transactionId' : [] | [string],
}
export interface PaymentReconciliationRow {
  'status' : string,
  'bookingId' : EntityId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amountCents' : bigint,
  'paymentId' : EntityId,
  'transactionId' : [] | [string],
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'refunded' : null } |
  { 'failed' : null };
export type RefundStatus = { 'pending' : null } |
  { 'nonRefundable' : null } |
  { 'refunded' : null } |
  { 'notApplicable' : null };
export interface ReserveSeatInput {
  'seatIds' : Array<EntityId>,
  'showtimeId' : EntityId,
}
export interface RevenueByEvent {
  'eventId' : EntityId,
  'totalBookings' : bigint,
  'eventTitle' : string,
  'totalRevenueCents' : bigint,
}
export interface SeatMapPublic {
  'cols' : bigint,
  'rows' : bigint,
  'showtimeId' : EntityId,
  'seats' : Array<SeatPublic>,
}
export interface SeatPublic {
  'id' : EntityId,
  'col' : bigint,
  'row' : bigint,
  'status' : SeatStatus,
  'bookingId' : [] | [EntityId],
  'showtimeId' : EntityId,
  'seatLabel' : string,
  'category' : TicketCategory,
}
export type SeatStatus = { 'blocked' : null } |
  { 'reserved' : null } |
  { 'booked' : null } |
  { 'available' : null };
export interface ShowtimeOccupancy {
  'startTime' : Timestamp,
  'occupancyPercent' : bigint,
  'showtimeId' : EntityId,
  'totalSeats' : bigint,
  'bookedSeats' : bigint,
  'eventTitle' : string,
}
export interface ShowtimePublic {
  'id' : EntityId,
  'startTime' : Timestamp,
  'eventId' : EntityId,
  'endTime' : Timestamp,
  'venueId' : EntityId,
  'seatCategories' : Array<ShowtimeSeatCategoryPublic>,
  'createdAt' : Timestamp,
  'isActive' : boolean,
}
export interface ShowtimeSeatCategoryPublic {
  'totalSeats' : bigint,
  'availableSeats' : bigint,
  'category' : TicketCategory,
  'priceInCents' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type TicketCategory = { 'vip' : null } |
  { 'balcony' : null } |
  { 'regular' : null };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateEventInput {
  'id' : EntityId,
  'title' : string,
  'imageUrls' : Array<string>,
  'description' : string,
  'genre' : string,
  'durationMinutes' : bigint,
  'eventType' : EventType,
}
export interface UpdateVenueInput {
  'id' : EntityId,
  'name' : string,
  'totalSeats' : bigint,
  'address' : string,
  'layoutCols' : bigint,
  'layoutRows' : bigint,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VenuePublic {
  'id' : EntityId,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'totalSeats' : bigint,
  'address' : string,
  'layoutCols' : bigint,
  'layoutRows' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockSeats' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'createBooking' : ActorMethod<[CreateBookingInput], bigint>,
  'createCheckoutSession' : ActorMethod<[bigint, string, string], string>,
  'createEvent' : ActorMethod<[CreateEventInput], bigint>,
  'createShowtime' : ActorMethod<[CreateShowtimeInput], bigint>,
  'createVenue' : ActorMethod<[CreateVenueInput], bigint>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'deleteShowtime' : ActorMethod<[bigint], undefined>,
  'deleteVenue' : ActorMethod<[bigint], undefined>,
  'getAdminAnalytics' : ActorMethod<[], AdminAnalytics>,
  'getBooking' : ActorMethod<[bigint], [] | [BookingPublic]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvent' : ActorMethod<[bigint], [] | [EventPublic]>,
  'getMyPayment' : ActorMethod<[bigint], [] | [PaymentPublic]>,
  'getPaymentReconciliation' : ActorMethod<[], Array<PaymentReconciliationRow>>,
  'getSeatMap' : ActorMethod<[bigint], SeatMapPublic>,
  'getShowtime' : ActorMethod<[bigint], [] | [ShowtimePublic]>,
  'getShowtimeOccupancy' : ActorMethod<[], Array<ShowtimeOccupancy>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'getVenue' : ActorMethod<[bigint], [] | [VenuePublic]>,
  'initializeShowtimeSeats' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllBookings' : ActorMethod<[], Array<BookingPublic>>,
  'listAllPayments' : ActorMethod<[], Array<PaymentPublic>>,
  'listBookingsByShowtime' : ActorMethod<[bigint], Array<BookingPublic>>,
  'listEvents' : ActorMethod<[[] | [EventFilter]], Array<EventPublic>>,
  'listMyBookings' : ActorMethod<[[] | [BookingFilter]], Array<BookingPublic>>,
  'listShowtimes' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<ShowtimePublic>
  >,
  'listVenues' : ActorMethod<[], Array<VenuePublic>>,
  'releaseReservation' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'reserveSeats' : ActorMethod<[ReserveSeatInput], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockSeats' : ActorMethod<[bigint, Array<bigint>], undefined>,
  'updateEvent' : ActorMethod<[UpdateEventInput], undefined>,
  'updateVenue' : ActorMethod<[UpdateVenueInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];