/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EntityId = IDL.Nat;
export const CreateBookingInput = IDL.Record({
  'seatIds' : IDL.Vec(EntityId),
  'showtimeId' : EntityId,
});
export const EventType = IDL.Variant({
  'movie' : IDL.Null,
  'concert' : IDL.Null,
  'workshop' : IDL.Null,
  'other' : IDL.Null,
  'sports' : IDL.Null,
});
export const CreateEventInput = IDL.Record({
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'eventType' : EventType,
});
export const Timestamp = IDL.Int;
export const TicketCategory = IDL.Variant({
  'vip' : IDL.Null,
  'balcony' : IDL.Null,
  'regular' : IDL.Null,
});
export const CreateShowtimeInput = IDL.Record({
  'startTime' : Timestamp,
  'eventId' : EntityId,
  'venueId' : EntityId,
  'seatCategories' : IDL.Vec(
    IDL.Record({
      'totalSeats' : IDL.Nat,
      'category' : TicketCategory,
      'priceInCents' : IDL.Nat,
    })
  ),
});
export const CreateVenueInput = IDL.Record({
  'name' : IDL.Text,
  'totalSeats' : IDL.Nat,
  'address' : IDL.Text,
  'layoutCols' : IDL.Nat,
  'layoutRows' : IDL.Nat,
});
export const RevenueByEvent = IDL.Record({
  'eventId' : EntityId,
  'totalBookings' : IDL.Nat,
  'eventTitle' : IDL.Text,
  'totalRevenueCents' : IDL.Nat,
});
export const ShowtimeOccupancy = IDL.Record({
  'startTime' : Timestamp,
  'occupancyPercent' : IDL.Nat,
  'showtimeId' : EntityId,
  'totalSeats' : IDL.Nat,
  'bookedSeats' : IDL.Nat,
  'eventTitle' : IDL.Text,
});
export const AdminAnalytics = IDL.Record({
  'popularEvents' : IDL.Vec(RevenueByEvent),
  'totalBookings' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'showtimeOccupancy' : IDL.Vec(ShowtimeOccupancy),
  'totalRevenueCents' : IDL.Nat,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const RefundStatus = IDL.Variant({
  'pending' : IDL.Null,
  'nonRefundable' : IDL.Null,
  'refunded' : IDL.Null,
  'notApplicable' : IDL.Null,
});
export const UserId = IDL.Principal;
export const BookingItem = IDL.Record({
  'seatId' : EntityId,
  'seatLabel' : IDL.Text,
  'category' : TicketCategory,
  'priceInCents' : IDL.Nat,
});
export const BookingPublic = IDL.Record({
  'id' : EntityId,
  'status' : BookingStatus,
  'refundStatus' : RefundStatus,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'showtimeId' : EntityId,
  'cancelledAt' : IDL.Opt(Timestamp),
  'qrReference' : IDL.Text,
  'totalAmountCents' : IDL.Nat,
  'items' : IDL.Vec(BookingItem),
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const EventPublic = IDL.Record({
  'id' : EntityId,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'genre' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'eventType' : EventType,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMode = IDL.Variant({
  'other' : IDL.Null,
  'card' : IDL.Null,
});
export const PaymentPublic = IDL.Record({
  'id' : EntityId,
  'status' : PaymentStatus,
  'completedAt' : IDL.Opt(Timestamp),
  'bookingId' : EntityId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amountCents' : IDL.Nat,
  'paymentMode' : PaymentMode,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'transactionId' : IDL.Opt(IDL.Text),
});
export const PaymentReconciliationRow = IDL.Record({
  'status' : IDL.Text,
  'bookingId' : EntityId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'amountCents' : IDL.Nat,
  'paymentId' : EntityId,
  'transactionId' : IDL.Opt(IDL.Text),
});
export const SeatStatus = IDL.Variant({
  'blocked' : IDL.Null,
  'reserved' : IDL.Null,
  'booked' : IDL.Null,
  'available' : IDL.Null,
});
export const SeatPublic = IDL.Record({
  'id' : EntityId,
  'col' : IDL.Nat,
  'row' : IDL.Nat,
  'status' : SeatStatus,
  'bookingId' : IDL.Opt(EntityId),
  'showtimeId' : EntityId,
  'seatLabel' : IDL.Text,
  'category' : TicketCategory,
});
export const SeatMapPublic = IDL.Record({
  'cols' : IDL.Nat,
  'rows' : IDL.Nat,
  'showtimeId' : EntityId,
  'seats' : IDL.Vec(SeatPublic),
});
export const ShowtimeSeatCategoryPublic = IDL.Record({
  'totalSeats' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'category' : TicketCategory,
  'priceInCents' : IDL.Nat,
});
export const ShowtimePublic = IDL.Record({
  'id' : EntityId,
  'startTime' : Timestamp,
  'eventId' : EntityId,
  'endTime' : Timestamp,
  'venueId' : EntityId,
  'seatCategories' : IDL.Vec(ShowtimeSeatCategoryPublic),
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const VenuePublic = IDL.Record({
  'id' : EntityId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'totalSeats' : IDL.Nat,
  'address' : IDL.Text,
  'layoutCols' : IDL.Nat,
  'layoutRows' : IDL.Nat,
});
export const EventFilter = IDL.Record({
  'title' : IDL.Opt(IDL.Text),
  'dateTo' : IDL.Opt(Timestamp),
  'venueId' : IDL.Opt(EntityId),
  'maxPriceCents' : IDL.Opt(IDL.Nat),
  'dateFrom' : IDL.Opt(Timestamp),
  'minPriceCents' : IDL.Opt(IDL.Nat),
  'eventType' : IDL.Opt(EventType),
});
export const BookingFilter = IDL.Record({
  'status' : IDL.Opt(BookingStatus),
  'showtimeId' : IDL.Opt(EntityId),
});
export const ReserveSeatInput = IDL.Record({
  'seatIds' : IDL.Vec(EntityId),
  'showtimeId' : EntityId,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateEventInput = IDL.Record({
  'id' : EntityId,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'genre' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'eventType' : EventType,
});
export const UpdateVenueInput = IDL.Record({
  'id' : EntityId,
  'name' : IDL.Text,
  'totalSeats' : IDL.Nat,
  'address' : IDL.Text,
  'layoutCols' : IDL.Nat,
  'layoutRows' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockSeats' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'createBooking' : IDL.Func([CreateBookingInput], [IDL.Nat], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEvent' : IDL.Func([CreateEventInput], [IDL.Nat], []),
  'createShowtime' : IDL.Func([CreateShowtimeInput], [IDL.Nat], []),
  'createVenue' : IDL.Func([CreateVenueInput], [IDL.Nat], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'deleteShowtime' : IDL.Func([IDL.Nat], [], []),
  'deleteVenue' : IDL.Func([IDL.Nat], [], []),
  'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(BookingPublic)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(EventPublic)], ['query']),
  'getMyPayment' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentPublic)], ['query']),
  'getPaymentReconciliation' : IDL.Func(
      [],
      [IDL.Vec(PaymentReconciliationRow)],
      ['query'],
    ),
  'getSeatMap' : IDL.Func([IDL.Nat], [SeatMapPublic], ['query']),
  'getShowtime' : IDL.Func([IDL.Nat], [IDL.Opt(ShowtimePublic)], ['query']),
  'getShowtimeOccupancy' : IDL.Func(
      [],
      [IDL.Vec(ShowtimeOccupancy)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getVenue' : IDL.Func([IDL.Nat], [IDL.Opt(VenuePublic)], ['query']),
  'initializeShowtimeSeats' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(BookingPublic)], ['query']),
  'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
  'listBookingsByShowtime' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(BookingPublic)],
      ['query'],
    ),
  'listEvents' : IDL.Func(
      [IDL.Opt(EventFilter)],
      [IDL.Vec(EventPublic)],
      ['query'],
    ),
  'listMyBookings' : IDL.Func(
      [IDL.Opt(BookingFilter)],
      [IDL.Vec(BookingPublic)],
      ['query'],
    ),
  'listShowtimes' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(ShowtimePublic)],
      ['query'],
    ),
  'listVenues' : IDL.Func([], [IDL.Vec(VenuePublic)], ['query']),
  'releaseReservation' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'reserveSeats' : IDL.Func([ReserveSeatInput], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockSeats' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
  'updateEvent' : IDL.Func([UpdateEventInput], [], []),
  'updateVenue' : IDL.Func([UpdateVenueInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EntityId = IDL.Nat;
  const CreateBookingInput = IDL.Record({
    'seatIds' : IDL.Vec(EntityId),
    'showtimeId' : EntityId,
  });
  const EventType = IDL.Variant({
    'movie' : IDL.Null,
    'concert' : IDL.Null,
    'workshop' : IDL.Null,
    'other' : IDL.Null,
    'sports' : IDL.Null,
  });
  const CreateEventInput = IDL.Record({
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'eventType' : EventType,
  });
  const Timestamp = IDL.Int;
  const TicketCategory = IDL.Variant({
    'vip' : IDL.Null,
    'balcony' : IDL.Null,
    'regular' : IDL.Null,
  });
  const CreateShowtimeInput = IDL.Record({
    'startTime' : Timestamp,
    'eventId' : EntityId,
    'venueId' : EntityId,
    'seatCategories' : IDL.Vec(
      IDL.Record({
        'totalSeats' : IDL.Nat,
        'category' : TicketCategory,
        'priceInCents' : IDL.Nat,
      })
    ),
  });
  const CreateVenueInput = IDL.Record({
    'name' : IDL.Text,
    'totalSeats' : IDL.Nat,
    'address' : IDL.Text,
    'layoutCols' : IDL.Nat,
    'layoutRows' : IDL.Nat,
  });
  const RevenueByEvent = IDL.Record({
    'eventId' : EntityId,
    'totalBookings' : IDL.Nat,
    'eventTitle' : IDL.Text,
    'totalRevenueCents' : IDL.Nat,
  });
  const ShowtimeOccupancy = IDL.Record({
    'startTime' : Timestamp,
    'occupancyPercent' : IDL.Nat,
    'showtimeId' : EntityId,
    'totalSeats' : IDL.Nat,
    'bookedSeats' : IDL.Nat,
    'eventTitle' : IDL.Text,
  });
  const AdminAnalytics = IDL.Record({
    'popularEvents' : IDL.Vec(RevenueByEvent),
    'totalBookings' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'showtimeOccupancy' : IDL.Vec(ShowtimeOccupancy),
    'totalRevenueCents' : IDL.Nat,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const RefundStatus = IDL.Variant({
    'pending' : IDL.Null,
    'nonRefundable' : IDL.Null,
    'refunded' : IDL.Null,
    'notApplicable' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const BookingItem = IDL.Record({
    'seatId' : EntityId,
    'seatLabel' : IDL.Text,
    'category' : TicketCategory,
    'priceInCents' : IDL.Nat,
  });
  const BookingPublic = IDL.Record({
    'id' : EntityId,
    'status' : BookingStatus,
    'refundStatus' : RefundStatus,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'showtimeId' : EntityId,
    'cancelledAt' : IDL.Opt(Timestamp),
    'qrReference' : IDL.Text,
    'totalAmountCents' : IDL.Nat,
    'items' : IDL.Vec(BookingItem),
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const EventPublic = IDL.Record({
    'id' : EntityId,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'genre' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'eventType' : EventType,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMode = IDL.Variant({ 'other' : IDL.Null, 'card' : IDL.Null });
  const PaymentPublic = IDL.Record({
    'id' : EntityId,
    'status' : PaymentStatus,
    'completedAt' : IDL.Opt(Timestamp),
    'bookingId' : EntityId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'amountCents' : IDL.Nat,
    'paymentMode' : PaymentMode,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const PaymentReconciliationRow = IDL.Record({
    'status' : IDL.Text,
    'bookingId' : EntityId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'amountCents' : IDL.Nat,
    'paymentId' : EntityId,
    'transactionId' : IDL.Opt(IDL.Text),
  });
  const SeatStatus = IDL.Variant({
    'blocked' : IDL.Null,
    'reserved' : IDL.Null,
    'booked' : IDL.Null,
    'available' : IDL.Null,
  });
  const SeatPublic = IDL.Record({
    'id' : EntityId,
    'col' : IDL.Nat,
    'row' : IDL.Nat,
    'status' : SeatStatus,
    'bookingId' : IDL.Opt(EntityId),
    'showtimeId' : EntityId,
    'seatLabel' : IDL.Text,
    'category' : TicketCategory,
  });
  const SeatMapPublic = IDL.Record({
    'cols' : IDL.Nat,
    'rows' : IDL.Nat,
    'showtimeId' : EntityId,
    'seats' : IDL.Vec(SeatPublic),
  });
  const ShowtimeSeatCategoryPublic = IDL.Record({
    'totalSeats' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'category' : TicketCategory,
    'priceInCents' : IDL.Nat,
  });
  const ShowtimePublic = IDL.Record({
    'id' : EntityId,
    'startTime' : Timestamp,
    'eventId' : EntityId,
    'endTime' : Timestamp,
    'venueId' : EntityId,
    'seatCategories' : IDL.Vec(ShowtimeSeatCategoryPublic),
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const VenuePublic = IDL.Record({
    'id' : EntityId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'totalSeats' : IDL.Nat,
    'address' : IDL.Text,
    'layoutCols' : IDL.Nat,
    'layoutRows' : IDL.Nat,
  });
  const EventFilter = IDL.Record({
    'title' : IDL.Opt(IDL.Text),
    'dateTo' : IDL.Opt(Timestamp),
    'venueId' : IDL.Opt(EntityId),
    'maxPriceCents' : IDL.Opt(IDL.Nat),
    'dateFrom' : IDL.Opt(Timestamp),
    'minPriceCents' : IDL.Opt(IDL.Nat),
    'eventType' : IDL.Opt(EventType),
  });
  const BookingFilter = IDL.Record({
    'status' : IDL.Opt(BookingStatus),
    'showtimeId' : IDL.Opt(EntityId),
  });
  const ReserveSeatInput = IDL.Record({
    'seatIds' : IDL.Vec(EntityId),
    'showtimeId' : EntityId,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateEventInput = IDL.Record({
    'id' : EntityId,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'genre' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'eventType' : EventType,
  });
  const UpdateVenueInput = IDL.Record({
    'id' : EntityId,
    'name' : IDL.Text,
    'totalSeats' : IDL.Nat,
    'address' : IDL.Text,
    'layoutCols' : IDL.Nat,
    'layoutRows' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockSeats' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'createBooking' : IDL.Func([CreateBookingInput], [IDL.Nat], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEvent' : IDL.Func([CreateEventInput], [IDL.Nat], []),
    'createShowtime' : IDL.Func([CreateShowtimeInput], [IDL.Nat], []),
    'createVenue' : IDL.Func([CreateVenueInput], [IDL.Nat], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'deleteShowtime' : IDL.Func([IDL.Nat], [], []),
    'deleteVenue' : IDL.Func([IDL.Nat], [], []),
    'getAdminAnalytics' : IDL.Func([], [AdminAnalytics], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [IDL.Opt(BookingPublic)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(EventPublic)], ['query']),
    'getMyPayment' : IDL.Func([IDL.Nat], [IDL.Opt(PaymentPublic)], ['query']),
    'getPaymentReconciliation' : IDL.Func(
        [],
        [IDL.Vec(PaymentReconciliationRow)],
        ['query'],
      ),
    'getSeatMap' : IDL.Func([IDL.Nat], [SeatMapPublic], ['query']),
    'getShowtime' : IDL.Func([IDL.Nat], [IDL.Opt(ShowtimePublic)], ['query']),
    'getShowtimeOccupancy' : IDL.Func(
        [],
        [IDL.Vec(ShowtimeOccupancy)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getVenue' : IDL.Func([IDL.Nat], [IDL.Opt(VenuePublic)], ['query']),
    'initializeShowtimeSeats' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(BookingPublic)], ['query']),
    'listAllPayments' : IDL.Func([], [IDL.Vec(PaymentPublic)], ['query']),
    'listBookingsByShowtime' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(BookingPublic)],
        ['query'],
      ),
    'listEvents' : IDL.Func(
        [IDL.Opt(EventFilter)],
        [IDL.Vec(EventPublic)],
        ['query'],
      ),
    'listMyBookings' : IDL.Func(
        [IDL.Opt(BookingFilter)],
        [IDL.Vec(BookingPublic)],
        ['query'],
      ),
    'listShowtimes' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(ShowtimePublic)],
        ['query'],
      ),
    'listVenues' : IDL.Func([], [IDL.Vec(VenuePublic)], ['query']),
    'releaseReservation' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'reserveSeats' : IDL.Func([ReserveSeatInput], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockSeats' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [], []),
    'updateEvent' : IDL.Func([UpdateEventInput], [], []),
    'updateVenue' : IDL.Func([UpdateVenueInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };