/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BookingItem {
    seatId: EntityId;
    seatLabel: string;
    category: TicketCategory;
    priceInCents: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShowtimeOccupancy {
    startTime: Timestamp;
    occupancyPercent: bigint;
    showtimeId: EntityId;
    totalSeats: bigint;
    bookedSeats: bigint;
    eventTitle: string;
}
export type EntityId = bigint;
export interface CreateBookingInput {
    seatIds: Array<EntityId>;
    showtimeId: EntityId;
}
export interface AdminAnalytics {
    popularEvents: Array<RevenueByEvent>;
    totalBookings: bigint;
    totalUsers: bigint;
    showtimeOccupancy: Array<ShowtimeOccupancy>;
    totalRevenueCents: bigint;
}
export interface SeatMapPublic {
    cols: bigint;
    rows: bigint;
    showtimeId: EntityId;
    seats: Array<SeatPublic>;
}
export interface ShowtimePublic {
    id: EntityId;
    startTime: Timestamp;
    eventId: EntityId;
    endTime: Timestamp;
    venueId: EntityId;
    seatCategories: Array<ShowtimeSeatCategoryPublic>;
    createdAt: Timestamp;
    isActive: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface BookingFilter {
    status?: BookingStatus;
    showtimeId?: EntityId;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface RevenueByEvent {
    eventId: EntityId;
    totalBookings: bigint;
    eventTitle: string;
    totalRevenueCents: bigint;
}
export interface EventPublic {
    id: EntityId;
    title: string;
    imageUrls: Array<string>;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    isActive: boolean;
    genre: string;
    durationMinutes: bigint;
    eventType: EventType;
}
export interface VenuePublic {
    id: EntityId;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    totalSeats: bigint;
    address: string;
    layoutCols: bigint;
    layoutRows: bigint;
}
export interface UpdateVenueInput {
    id: EntityId;
    name: string;
    totalSeats: bigint;
    address: string;
    layoutCols: bigint;
    layoutRows: bigint;
}
export interface UpdateEventInput {
    id: EntityId;
    title: string;
    imageUrls: Array<string>;
    description: string;
    genre: string;
    durationMinutes: bigint;
    eventType: EventType;
}
export interface PaymentPublic {
    id: EntityId;
    status: PaymentStatus;
    completedAt?: Timestamp;
    bookingId: EntityId;
    userId: UserId;
    createdAt: Timestamp;
    amountCents: bigint;
    paymentMode: PaymentMode;
    stripeSessionId?: string;
    transactionId?: string;
}
export interface EventFilter {
    title?: string;
    dateTo?: Timestamp;
    venueId?: EntityId;
    maxPriceCents?: bigint;
    dateFrom?: Timestamp;
    minPriceCents?: bigint;
    eventType?: EventType;
}
export interface BookingPublic {
    id: EntityId;
    status: BookingStatus;
    refundStatus: RefundStatus;
    userId: UserId;
    createdAt: Timestamp;
    showtimeId: EntityId;
    cancelledAt?: Timestamp;
    qrReference: string;
    totalAmountCents: bigint;
    items: Array<BookingItem>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface UserProfilePublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    email: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type UserId = Principal;
export interface CreateVenueInput {
    name: string;
    totalSeats: bigint;
    address: string;
    layoutCols: bigint;
    layoutRows: bigint;
}
export interface ReserveSeatInput {
    seatIds: Array<EntityId>;
    showtimeId: EntityId;
}
export interface CreateEventInput {
    title: string;
    imageUrls: Array<string>;
    description: string;
    genre: string;
    durationMinutes: bigint;
    eventType: EventType;
}
export interface ShowtimeSeatCategoryPublic {
    totalSeats: bigint;
    availableSeats: bigint;
    category: TicketCategory;
    priceInCents: bigint;
}
export interface PaymentReconciliationRow {
    status: string;
    bookingId: EntityId;
    userId: UserId;
    createdAt: Timestamp;
    amountCents: bigint;
    paymentId: EntityId;
    transactionId?: string;
}
export interface SeatPublic {
    id: EntityId;
    col: bigint;
    row: bigint;
    status: SeatStatus;
    bookingId?: EntityId;
    showtimeId: EntityId;
    seatLabel: string;
    category: TicketCategory;
}
export interface CreateShowtimeInput {
    startTime: Timestamp;
    eventId: EntityId;
    venueId: EntityId;
    seatCategories: Array<{
        totalSeats: bigint;
        category: TicketCategory;
        priceInCents: bigint;
    }>;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum EventType {
    movie = "movie",
    concert = "concert",
    workshop = "workshop",
    other = "other",
    sports = "sports"
}
export enum PaymentMode {
    other = "other",
    card = "card"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded",
    failed = "failed"
}
export enum RefundStatus {
    pending = "pending",
    nonRefundable = "nonRefundable",
    refunded = "refunded",
    notApplicable = "notApplicable"
}
export enum SeatStatus {
    blocked = "blocked",
    reserved = "reserved",
    booked = "booked",
    available = "available"
}
export enum TicketCategory {
    vip = "vip",
    balcony = "balcony",
    regular = "regular"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    blockSeats(showtimeId: bigint, seatIds: Array<bigint>): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<void>;
    createBooking(input: CreateBookingInput): Promise<bigint>;
    createCheckoutSession(bookingId: bigint, successUrl: string, cancelUrl: string): Promise<string>;
    createEvent(input: CreateEventInput): Promise<bigint>;
    createShowtime(input: CreateShowtimeInput): Promise<bigint>;
    createVenue(input: CreateVenueInput): Promise<bigint>;
    deleteEvent(eventId: bigint): Promise<void>;
    deleteShowtime(showtimeId: bigint): Promise<void>;
    deleteVenue(venueId: bigint): Promise<void>;
    getAdminAnalytics(): Promise<AdminAnalytics>;
    getBooking(bookingId: bigint): Promise<BookingPublic | null>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEvent(eventId: bigint): Promise<EventPublic | null>;
    getMyPayment(bookingId: bigint): Promise<PaymentPublic | null>;
    getPaymentReconciliation(): Promise<Array<PaymentReconciliationRow>>;
    getSeatMap(showtimeId: bigint): Promise<SeatMapPublic>;
    getShowtime(showtimeId: bigint): Promise<ShowtimePublic | null>;
    getShowtimeOccupancy(): Promise<Array<ShowtimeOccupancy>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfilePublic | null>;
    getVenue(venueId: bigint): Promise<VenuePublic | null>;
    initializeShowtimeSeats(showtimeId: bigint): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllBookings(): Promise<Array<BookingPublic>>;
    listAllPayments(): Promise<Array<PaymentPublic>>;
    listBookingsByShowtime(showtimeId: bigint): Promise<Array<BookingPublic>>;
    listEvents(filter: EventFilter | null): Promise<Array<EventPublic>>;
    listMyBookings(filter: BookingFilter | null): Promise<Array<BookingPublic>>;
    listShowtimes(eventId: bigint | null, venueId: bigint | null): Promise<Array<ShowtimePublic>>;
    listVenues(): Promise<Array<VenuePublic>>;
    releaseReservation(showtimeId: bigint, seatIds: Array<bigint>): Promise<void>;
    reserveSeats(input: ReserveSeatInput): Promise<void>;
    saveCallerUserProfile(name: string, email: string): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unblockSeats(showtimeId: bigint, seatIds: Array<bigint>): Promise<void>;
    updateEvent(input: UpdateEventInput): Promise<void>;
    updateVenue(input: UpdateVenueInput): Promise<void>;
}
import type { BookingFilter as _BookingFilter, BookingItem as _BookingItem, BookingPublic as _BookingPublic, BookingStatus as _BookingStatus, CreateEventInput as _CreateEventInput, CreateShowtimeInput as _CreateShowtimeInput, EntityId as _EntityId, EventFilter as _EventFilter, EventPublic as _EventPublic, EventType as _EventType, PaymentMode as _PaymentMode, PaymentPublic as _PaymentPublic, PaymentReconciliationRow as _PaymentReconciliationRow, PaymentStatus as _PaymentStatus, RefundStatus as _RefundStatus, SeatMapPublic as _SeatMapPublic, SeatPublic as _SeatPublic, SeatStatus as _SeatStatus, ShowtimePublic as _ShowtimePublic, ShowtimeSeatCategoryPublic as _ShowtimeSeatCategoryPublic, StripeSessionStatus as _StripeSessionStatus, TicketCategory as _TicketCategory, Timestamp as _Timestamp, UpdateEventInput as _UpdateEventInput, UserId as _UserId, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, VenuePublic as _VenuePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async blockSeats(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.blockSeats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.blockSeats(arg0, arg1);
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: CreateBookingInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: bigint, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createEvent(arg0: CreateEventInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_CreateEventInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_CreateEventInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createShowtime(arg0: CreateShowtimeInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createShowtime(to_candid_CreateShowtimeInput_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShowtime(to_candid_CreateShowtimeInput_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createVenue(arg0: CreateVenueInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createVenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVenue(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteShowtime(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShowtime(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShowtime(arg0);
            return result;
        }
    }
    async deleteVenue(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVenue(arg0);
            return result;
        }
    }
    async getAdminAnalytics(): Promise<AdminAnalytics> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAnalytics();
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<BookingPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<EventPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPayment(arg0: bigint): Promise<PaymentPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPayment(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPayment(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentReconciliation(): Promise<Array<PaymentReconciliationRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentReconciliation();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentReconciliation();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSeatMap(arg0: bigint): Promise<SeatMapPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeatMap(arg0);
                return from_candid_SeatMapPublic_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeatMap(arg0);
            return from_candid_SeatMapPublic_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShowtime(arg0: bigint): Promise<ShowtimePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShowtime(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShowtime(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShowtimeOccupancy(): Promise<Array<ShowtimeOccupancy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShowtimeOccupancy();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShowtimeOccupancy();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVenue(arg0: bigint): Promise<VenuePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVenue(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVenue(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeShowtimeSeats(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeShowtimeSeats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeShowtimeSeats(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllBookings(): Promise<Array<BookingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllPayments(): Promise<Array<PaymentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPayments();
                return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPayments();
            return from_candid_vec_n64(this._uploadFile, this._downloadFile, result);
        }
    }
    async listBookingsByShowtime(arg0: bigint): Promise<Array<BookingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBookingsByShowtime(arg0);
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBookingsByShowtime(arg0);
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEvents(arg0: EventFilter | null): Promise<Array<EventPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents(to_candid_opt_n65(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents(to_candid_opt_n65(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyBookings(arg0: BookingFilter | null): Promise<Array<BookingPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBookings(to_candid_opt_n69(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBookings(to_candid_opt_n69(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async listShowtimes(arg0: bigint | null, arg1: bigint | null): Promise<Array<ShowtimePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listShowtimes(to_candid_opt_n74(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n74(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listShowtimes(to_candid_opt_n74(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n74(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVenues(): Promise<Array<VenuePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVenues();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVenues();
            return result;
        }
    }
    async releaseReservation(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseReservation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseReservation(arg0, arg1);
            return result;
        }
    }
    async reserveSeats(arg0: ReserveSeatInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reserveSeats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reserveSeats(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unblockSeats(arg0: bigint, arg1: Array<bigint>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unblockSeats(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unblockSeats(arg0, arg1);
            return result;
        }
    }
    async updateEvent(arg0: UpdateEventInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(to_candid_UpdateEventInput_n76(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(to_candid_UpdateEventInput_n76(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateVenue(arg0: UpdateVenueInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVenue(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVenue(arg0);
            return result;
        }
    }
}
function from_candid_BookingItem_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingItem): BookingItem {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_BookingPublic_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingPublic): BookingPublic {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_EventPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventPublic): EventPublic {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentPublic_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentPublic): PaymentPublic {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentReconciliationRow_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentReconciliationRow): PaymentReconciliationRow {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_RefundStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefundStatus): RefundStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SeatMapPublic_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeatMapPublic): SeatMapPublic {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SeatPublic_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeatPublic): SeatPublic {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_SeatStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeatStatus): SeatStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_ShowtimePublic_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShowtimePublic): ShowtimePublic {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ShowtimeSeatCategoryPublic_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShowtimeSeatCategoryPublic): ShowtimeSeatCategoryPublic {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_TicketCategory_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketCategory): TicketCategory {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BookingPublic]): BookingPublic | null {
    return value.length === 0 ? null : from_candid_BookingPublic_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EventPublic]): EventPublic | null {
    return value.length === 0 ? null : from_candid_EventPublic_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentPublic]): PaymentPublic | null {
    return value.length === 0 ? null : from_candid_PaymentPublic_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntityId]): EntityId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShowtimePublic]): ShowtimePublic | null {
    return value.length === 0 ? null : from_candid_ShowtimePublic_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VenuePublic]): VenuePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _BookingStatus;
    refundStatus: _RefundStatus;
    userId: _UserId;
    createdAt: _Timestamp;
    showtimeId: _EntityId;
    cancelledAt: [] | [_Timestamp];
    qrReference: string;
    totalAmountCents: bigint;
    items: Array<_BookingItem>;
}): {
    id: EntityId;
    status: BookingStatus;
    refundStatus: RefundStatus;
    userId: UserId;
    createdAt: Timestamp;
    showtimeId: EntityId;
    cancelledAt?: Timestamp;
    qrReference: string;
    totalAmountCents: bigint;
    items: Array<BookingItem>;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n16(_uploadFile, _downloadFile, value.status),
        refundStatus: from_candid_RefundStatus_n18(_uploadFile, _downloadFile, value.refundStatus),
        userId: value.userId,
        createdAt: value.createdAt,
        showtimeId: value.showtimeId,
        cancelledAt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.cancelledAt)),
        qrReference: value.qrReference,
        totalAmountCents: value.totalAmountCents,
        items: from_candid_vec_n21(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seatId: _EntityId;
    seatLabel: string;
    category: _TicketCategory;
    priceInCents: bigint;
}): {
    seatId: EntityId;
    seatLabel: string;
    category: TicketCategory;
    priceInCents: bigint;
} {
    return {
        seatId: value.seatId,
        seatLabel: value.seatLabel,
        category: from_candid_TicketCategory_n24(_uploadFile, _downloadFile, value.category),
        priceInCents: value.priceInCents
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    title: string;
    imageUrls: Array<string>;
    createdAt: _Timestamp;
    createdBy: _UserId;
    description: string;
    isActive: boolean;
    genre: string;
    durationMinutes: bigint;
    eventType: _EventType;
}): {
    id: EntityId;
    title: string;
    imageUrls: Array<string>;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    isActive: boolean;
    genre: string;
    durationMinutes: bigint;
    eventType: EventType;
} {
    return {
        id: value.id,
        title: value.title,
        imageUrls: value.imageUrls,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        isActive: value.isActive,
        genre: value.genre,
        durationMinutes: value.durationMinutes,
        eventType: from_candid_EventType_n32(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _PaymentStatus;
    completedAt: [] | [_Timestamp];
    bookingId: _EntityId;
    userId: _UserId;
    createdAt: _Timestamp;
    amountCents: bigint;
    paymentMode: _PaymentMode;
    stripeSessionId: [] | [string];
    transactionId: [] | [string];
}): {
    id: EntityId;
    status: PaymentStatus;
    completedAt?: Timestamp;
    bookingId: EntityId;
    userId: UserId;
    createdAt: Timestamp;
    amountCents: bigint;
    paymentMode: PaymentMode;
    stripeSessionId?: string;
    transactionId?: string;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n37(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.completedAt)),
        bookingId: value.bookingId,
        userId: value.userId,
        createdAt: value.createdAt,
        amountCents: value.amountCents,
        paymentMode: from_candid_PaymentMode_n39(_uploadFile, _downloadFile, value.paymentMode),
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.stripeSessionId)),
        transactionId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    bookingId: _EntityId;
    userId: _UserId;
    createdAt: _Timestamp;
    amountCents: bigint;
    paymentId: _EntityId;
    transactionId: [] | [string];
}): {
    status: string;
    bookingId: EntityId;
    userId: UserId;
    createdAt: Timestamp;
    amountCents: bigint;
    paymentId: EntityId;
    transactionId?: string;
} {
    return {
        status: value.status,
        bookingId: value.bookingId,
        userId: value.userId,
        createdAt: value.createdAt,
        amountCents: value.amountCents,
        paymentId: value.paymentId,
        transactionId: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.transactionId))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cols: bigint;
    rows: bigint;
    showtimeId: _EntityId;
    seats: Array<_SeatPublic>;
}): {
    cols: bigint;
    rows: bigint;
    showtimeId: EntityId;
    seats: Array<SeatPublic>;
} {
    return {
        cols: value.cols,
        rows: value.rows,
        showtimeId: value.showtimeId,
        seats: from_candid_vec_n47(_uploadFile, _downloadFile, value.seats)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    col: bigint;
    row: bigint;
    status: _SeatStatus;
    bookingId: [] | [_EntityId];
    showtimeId: _EntityId;
    seatLabel: string;
    category: _TicketCategory;
}): {
    id: EntityId;
    col: bigint;
    row: bigint;
    status: SeatStatus;
    bookingId?: EntityId;
    showtimeId: EntityId;
    seatLabel: string;
    category: TicketCategory;
} {
    return {
        id: value.id,
        col: value.col,
        row: value.row,
        status: from_candid_SeatStatus_n50(_uploadFile, _downloadFile, value.status),
        bookingId: record_opt_to_undefined(from_candid_opt_n52(_uploadFile, _downloadFile, value.bookingId)),
        showtimeId: value.showtimeId,
        seatLabel: value.seatLabel,
        category: from_candid_TicketCategory_n24(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    startTime: _Timestamp;
    eventId: _EntityId;
    endTime: _Timestamp;
    venueId: _EntityId;
    seatCategories: Array<_ShowtimeSeatCategoryPublic>;
    createdAt: _Timestamp;
    isActive: boolean;
}): {
    id: EntityId;
    startTime: Timestamp;
    eventId: EntityId;
    endTime: Timestamp;
    venueId: EntityId;
    seatCategories: Array<ShowtimeSeatCategoryPublic>;
    createdAt: Timestamp;
    isActive: boolean;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        eventId: value.eventId,
        endTime: value.endTime,
        venueId: value.venueId,
        seatCategories: from_candid_vec_n56(_uploadFile, _downloadFile, value.seatCategories),
        createdAt: value.createdAt,
        isActive: value.isActive
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalSeats: bigint;
    availableSeats: bigint;
    category: _TicketCategory;
    priceInCents: bigint;
}): {
    totalSeats: bigint;
    availableSeats: bigint;
    category: TicketCategory;
    priceInCents: bigint;
} {
    return {
        totalSeats: value.totalSeats,
        availableSeats: value.availableSeats,
        category: from_candid_TicketCategory_n24(_uploadFile, _downloadFile, value.category),
        priceInCents: value.priceInCents
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n41(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    nonRefundable: null;
} | {
    refunded: null;
} | {
    notApplicable: null;
}): RefundStatus {
    return "pending" in value ? RefundStatus.pending : "nonRefundable" in value ? RefundStatus.nonRefundable : "refunded" in value ? RefundStatus.refunded : "notApplicable" in value ? RefundStatus.notApplicable : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    vip: null;
} | {
    balcony: null;
} | {
    regular: null;
}): TicketCategory {
    return "vip" in value ? TicketCategory.vip : "balcony" in value ? TicketCategory.balcony : "regular" in value ? TicketCategory.regular : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    movie: null;
} | {
    concert: null;
} | {
    workshop: null;
} | {
    other: null;
} | {
    sports: null;
}): EventType {
    return "movie" in value ? EventType.movie : "concert" in value ? EventType.concert : "workshop" in value ? EventType.workshop : "other" in value ? EventType.other : "sports" in value ? EventType.sports : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    card: null;
}): PaymentMode {
    return "other" in value ? PaymentMode.other : "card" in value ? PaymentMode.card : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blocked: null;
} | {
    reserved: null;
} | {
    booked: null;
} | {
    available: null;
}): SeatStatus {
    return "blocked" in value ? SeatStatus.blocked : "reserved" in value ? SeatStatus.reserved : "booked" in value ? SeatStatus.booked : "available" in value ? SeatStatus.available : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n61(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingItem>): Array<BookingItem> {
    return value.map((x)=>from_candid_BookingItem_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentReconciliationRow>): Array<PaymentReconciliationRow> {
    return value.map((x)=>from_candid_PaymentReconciliationRow_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SeatPublic>): Array<SeatPublic> {
    return value.map((x)=>from_candid_SeatPublic_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShowtimeSeatCategoryPublic>): Array<ShowtimeSeatCategoryPublic> {
    return value.map((x)=>from_candid_ShowtimeSeatCategoryPublic_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingPublic>): Array<BookingPublic> {
    return value.map((x)=>from_candid_BookingPublic_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentPublic>): Array<PaymentPublic> {
    return value.map((x)=>from_candid_PaymentPublic_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EventPublic>): Array<EventPublic> {
    return value.map((x)=>from_candid_EventPublic_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShowtimePublic>): Array<ShowtimePublic> {
    return value.map((x)=>from_candid_ShowtimePublic_n54(_uploadFile, _downloadFile, x));
}
function to_candid_BookingFilter_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingFilter): _BookingFilter {
    return to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function to_candid_CreateEventInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEventInput): _CreateEventInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateShowtimeInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateShowtimeInput): _CreateShowtimeInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_EventFilter_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter): _EventFilter {
    return to_candid_record_n67(_uploadFile, _downloadFile, value);
}
function to_candid_EventType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TicketCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketCategory): _TicketCategory {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateEventInput_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateEventInput): _UpdateEventInput {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventFilter | null): [] | [_EventFilter] {
    return value === null ? candid_none() : candid_some(to_candid_EventFilter_n66(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingFilter | null): [] | [_BookingFilter] {
    return value === null ? candid_none() : candid_some(to_candid_BookingFilter_n70(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalSeats: bigint;
    category: TicketCategory;
    priceInCents: bigint;
}): {
    totalSeats: bigint;
    category: _TicketCategory;
    priceInCents: bigint;
} {
    return {
        totalSeats: value.totalSeats,
        category: to_candid_TicketCategory_n11(_uploadFile, _downloadFile, value.category),
        priceInCents: value.priceInCents
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    imageUrls: Array<string>;
    description: string;
    genre: string;
    durationMinutes: bigint;
    eventType: EventType;
}): {
    title: string;
    imageUrls: Array<string>;
    description: string;
    genre: string;
    durationMinutes: bigint;
    eventType: _EventType;
} {
    return {
        title: value.title,
        imageUrls: value.imageUrls,
        description: value.description,
        genre: value.genre,
        durationMinutes: value.durationMinutes,
        eventType: to_candid_EventType_n5(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title?: string;
    dateTo?: Timestamp;
    venueId?: EntityId;
    maxPriceCents?: bigint;
    dateFrom?: Timestamp;
    minPriceCents?: bigint;
    eventType?: EventType;
}): {
    title: [] | [string];
    dateTo: [] | [_Timestamp];
    venueId: [] | [_EntityId];
    maxPriceCents: [] | [bigint];
    dateFrom: [] | [_Timestamp];
    minPriceCents: [] | [bigint];
    eventType: [] | [_EventType];
} {
    return {
        title: value.title ? candid_some(value.title) : candid_none(),
        dateTo: value.dateTo ? candid_some(value.dateTo) : candid_none(),
        venueId: value.venueId ? candid_some(value.venueId) : candid_none(),
        maxPriceCents: value.maxPriceCents ? candid_some(value.maxPriceCents) : candid_none(),
        dateFrom: value.dateFrom ? candid_some(value.dateFrom) : candid_none(),
        minPriceCents: value.minPriceCents ? candid_some(value.minPriceCents) : candid_none(),
        eventType: value.eventType ? candid_some(to_candid_EventType_n5(_uploadFile, _downloadFile, value.eventType)) : candid_none()
    };
}
function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: BookingStatus;
    showtimeId?: EntityId;
}): {
    status: [] | [_BookingStatus];
    showtimeId: [] | [_EntityId];
} {
    return {
        status: value.status ? candid_some(to_candid_BookingStatus_n72(_uploadFile, _downloadFile, value.status)) : candid_none(),
        showtimeId: value.showtimeId ? candid_some(value.showtimeId) : candid_none()
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EntityId;
    title: string;
    imageUrls: Array<string>;
    description: string;
    genre: string;
    durationMinutes: bigint;
    eventType: EventType;
}): {
    id: _EntityId;
    title: string;
    imageUrls: Array<string>;
    description: string;
    genre: string;
    durationMinutes: bigint;
    eventType: _EventType;
} {
    return {
        id: value.id,
        title: value.title,
        imageUrls: value.imageUrls,
        description: value.description,
        genre: value.genre,
        durationMinutes: value.durationMinutes,
        eventType: to_candid_EventType_n5(_uploadFile, _downloadFile, value.eventType)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startTime: Timestamp;
    eventId: EntityId;
    venueId: EntityId;
    seatCategories: Array<{
        totalSeats: bigint;
        category: TicketCategory;
        priceInCents: bigint;
    }>;
}): {
    startTime: _Timestamp;
    eventId: _EntityId;
    venueId: _EntityId;
    seatCategories: Array<{
        totalSeats: bigint;
        category: _TicketCategory;
        priceInCents: bigint;
    }>;
} {
    return {
        startTime: value.startTime,
        eventId: value.eventId,
        venueId: value.venueId,
        seatCategories: to_candid_vec_n9(_uploadFile, _downloadFile, value.seatCategories)
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketCategory): {
    vip: null;
} | {
    balcony: null;
} | {
    regular: null;
} {
    return value == TicketCategory.vip ? {
        vip: null
    } : value == TicketCategory.balcony ? {
        balcony: null
    } : value == TicketCategory.regular ? {
        regular: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    movie: null;
} | {
    concert: null;
} | {
    workshop: null;
} | {
    other: null;
} | {
    sports: null;
} {
    return value == EventType.movie ? {
        movie: null
    } : value == EventType.concert ? {
        concert: null
    } : value == EventType.workshop ? {
        workshop: null
    } : value == EventType.other ? {
        other: null
    } : value == EventType.sports ? {
        sports: null
    } : value;
}
function to_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    totalSeats: bigint;
    category: TicketCategory;
    priceInCents: bigint;
}>): Array<{
    totalSeats: bigint;
    category: _TicketCategory;
    priceInCents: bigint;
}> {
    return value.map((x)=>to_candid_record_n10(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
